### PR TITLE
Redis and SSL Observability Demo Code

### PR DESCRIPTION
**Pull request by dorkamotorka**

### CODE REVIEW

**Comment by dorkamotorka** [comment]
Can request a reviewer, so mentioning here: @kenanfarukcakir @fatihbaltaci

**Comment by kenanfarukcakir** [comment]
Could add prerequisites in README.md. I was trying to follow the instructions on a machine that I've not compiled a bpf code before and was able to got `go generate` command working after resolving following errors:  `llvm-strip not found` and `In file included from /usr/include/linux/bpf.h:11:
/usr/include/linux/types.h:5:10: fatal error: 'asm/types.h' file not found` errors separately. 

I've installed kernel-headers, clang, llvm and gcc-multilib.

**Comment by kenanfarukcakir** [comment]
We do track redis pub/sub communication too. We can add it to test client, it is classified as `REDIS_PUSHED_EVENT` on bpf side.

**Comment by dorkamotorka** [comment]
@kenanfarukcakir Thank you for your input - I've added the requested stuff. Note that I've also started to work on SSL and it added it to this PR automatically - which is slightly misfortunate but still.

**Pull request merged**
